language: go

dist: xenial

go:
  - 1.12

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out
