package fs_test

// This file contains tests for bugs identified in the staff engineer code review.
// Every test in this file is expected to FAIL until the corresponding bug is fixed.
//
// B1 — IndexDB has no mutex: concurrent Update calls lose data (TOCTOU)
// B2 — CRLHolder.Get silently returns empty RevocationList for a corrupt crl.pem
//       instead of returning an error, making revoked certs appear valid.

import (
	"math/big"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	fs "github.com/kemsta/go-easyrsa/storage/fs"
	"github.com/kemsta/go-easyrsa/storage"
)

// TestIndexDB_ConcurrentUpdate_AllUpdatesApplied — B1
//
// IndexDB.Update on the fs backend performs a read-modify-write cycle
// without holding a mutex. When N goroutines call Update simultaneously
// they all read the same snapshot, each writes back its own single-entry
// modification, and the last writer wins — every earlier modification is
// silently discarded.
//
// Expected (correct): all N entries end up StatusRevoked.
// Actual (buggy):     only ~1 entry is revoked; the rest are lost.
func TestIndexDB_ConcurrentUpdate_AllUpdatesApplied(t *testing.T) {
	dir := t.TempDir()
	db := fs.NewIndexDB(dir)
	sp := fs.NewSerialProvider(dir)

	const N = 20
	serials := make([]*big.Int, N)
	expires := time.Now().Add(24 * time.Hour)

	for i := 0; i < N; i++ {
		s, err := sp.Next()
		require.NoError(t, err)
		serials[i] = s
		require.NoError(t, db.Record(storage.IndexEntry{
			Status:    storage.StatusValid,
			Serial:    s,
			ExpiresAt: expires,
		}))
	}

	// Release all goroutines simultaneously to maximise interleaving.
	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(N)
	now := time.Now()
	for i := 0; i < N; i++ {
		i := i
		go func() {
			defer wg.Done()
			<-start
			_ = db.Update(serials[i], storage.StatusRevoked, now, 0)
		}()
	}
	close(start)
	wg.Wait()

	revokedStatus := storage.StatusRevoked
	results, err := db.Query(storage.IndexFilter{Status: &revokedStatus})
	require.NoError(t, err)
	assert.Len(t, results, N,
		"all %d concurrent Updates must be persisted; "+
			"fewer entries means the TOCTOU race in IndexDB.Update caused lost writes", N)
}

// TestCRLHolder_Get_CorruptPEMReturnsError — B2
//
// If crl.pem exists but contains no valid PEM block (e.g. partial write,
// manual corruption), CRLHolder.Get currently returns an empty
// RevocationList with nil error instead of an error.
//
// The consequence: all revoked certificates silently appear valid to any
// caller that checks the CRL (VerifyCert, IsRevoked) until crl.pem is
// regenerated by a successful GenCRL call.
//
// Expected (correct): Get returns a non-nil error.
// Actual (buggy):     Get returns (&x509.RevocationList{}, nil).
func TestCRLHolder_Get_CorruptPEMReturnsError(t *testing.T) {
	dir := t.TempDir()

	// Simulate a crl.pem left in a corrupt state (e.g. process killed mid-write
	// before the atomic rename was introduced, or external file corruption).
	corrupt := []byte("this is not a valid PEM block — file was truncated mid-write")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "crl.pem"), corrupt, 0644))

	ch := fs.NewCRLHolder(dir)
	_, err := ch.Get()
	assert.Error(t, err,
		"Get() on a corrupt crl.pem must return an error; "+
			"returning an empty RevocationList allows revoked certs to appear valid")
}
