on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3.6.0
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
      - uses: actions/checkout@v3.6.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v3.6.0
      - name: Calc coverage
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
